services:
  exporter:
    image: mail-exporter:local
    build:
      context: .
      dockerfile: ./exporter/Dockerfile
      target: development
    environment:
      MAIL_ACCOUNTS_JSON: ${MAIL_ACCOUNTS_JSON:-[]}
      SECURE: ${SECURE:-false}
      KEEP_HTML: ${KEEP_HTML:-false}
    volumes:
      - ./exporter:/app
      - ./output:/output
