services:
  exporter:
    image: mail-exporter:prod
    build:
      context: .
      dockerfile: ./exporter/Dockerfile
      target: production
    environment:
      MAIL_ACCOUNTS_JSON: ${MAIL_ACCOUNTS_JSON:-[]}
      SECURE: ${SECURE:-false}
    volumes:
      - ./output:/output
